### ISSUE TITLE
I/O error reading PNG header

### ISSUE THREAD

**Issue by LefterisL** [beansoft/react-native-console#64] opened 2021-05-21 09:21 UTC
I know this is supposed to be fixed on a previous version but here we go again

OS: Windows 10
React Native Console ( 2021.1.7 )
Webstorm - 2021.1.1
npm - 7.8.0
node - v14.16.0

```
javax.imageio.IIOException: I/O error reading PNG header!
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readHeader(PNGImageReader.java:315)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:698)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1395)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1810)
	at com.intellij.util.ImageLoader.loadPng(ImageLoader.java:352)
	at com.intellij.util.ImageLoader.loadFromStream(ImageLoader.java:547)
	at com.intellij.util.ImageLoader.loadFromBytes(ImageLoader.java:538)
	at lermitage.intellij.iconviewer.ImageIconProvider.previewImage(ImageIconProvider.java:136)
	at lermitage.intellij.iconviewer.ImageIconProvider.getIcon(ImageIconProvider.java:70)
	at com.github.beansoftapp.reatnative.idea.project.RNIconProvider.getIcon(RNIconProvider.java:45)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:222)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:155)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:141)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:299)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:185)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:110)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:185)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:100)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$5(DeferredIconImpl.java:184)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.imageio.IIOException: Bad PNG signature!
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readHeader(PNGImageReader.java:242)
	... 47 more
```

**Comment by beansoft** [comment] 2021-05-21 09:52
Thx for your report, I’ll take a look at and fix it soon, it should be a regression.




On 05/21/2021 ***@***.***> wrote：

I know this is supposed to be fixed on a previous version but here we go again

OS: Windows 10
React Native Console ( 2021.1.7 )
Webstorm - 2021.1.1
npm - 7.8.0
node - v14.16.0

javax.imageio.IIOException: I/O error reading PNG header!
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readHeader(PNGImageReader.java:315)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:698)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1395)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1810)
	at com.intellij.util.ImageLoader.loadPng(ImageLoader.java:352)
	at com.intellij.util.ImageLoader.loadFromStream(ImageLoader.java:547)
	at com.intellij.util.ImageLoader.loadFromBytes(ImageLoader.java:538)
	at lermitage.intellij.iconviewer.ImageIconProvider.previewImage(ImageIconProvider.java:136)
	at lermitage.intellij.iconviewer.ImageIconProvider.getIcon(ImageIconProvider.java:70)
	at com.github.beansoftapp.reatnative.idea.project.RNIconProvider.getIcon(RNIconProvider.java:45)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:222)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:155)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:141)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:299)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:185)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:110)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:185)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:100)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$5(DeferredIconImpl.java:184)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.imageio.IIOException: Bad PNG signature!
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readHeader(PNGImageReader.java:242)
	... 47 more

**Comment by beansoft** [comment] 2021-05-22 03:03
I’ve fixed it, please download to your disk and install it, have a try before it’s approved:


https://plugins.jetbrains.com/plugin/download?rel=true&updateId=120298

**Closed** 2021-07-27 13:13 UTC
